"""D3 centralized rolling assignment planner.

This package is for offline research simulation and human-review candidate
planning only. It intentionally excludes real fire-control parameters, damage
logic, hardware drivers, autonomous disposition, and authorization bypasses.
"""

from .costs import CostMatrixResult, CostModel
from .fixtures import (
    P1_ASSIGNMENT_FIXTURE_PROFILE_ID,
    P1_ASSIGNMENT_FIXTURE_PROFILE_VERSION,
    P1_ASSIGNMENT_FIXTURE_SCHEMA,
    AssignmentFixtureStep,
    AssignmentScenarioFixture,
    build_p1_assignment_fixtures,
    p1_assignment_fixture_by_id,
)
from .airsim_dry_run_adapter import (
    AirSimDryRunAssignmentAdapter,
    adapt_airsim_global_tracks,
    adapt_airsim_resource_states,
)
from .models import (
    ASSIGNMENT_CALIBRATION_PROFILE_SCHEMA_V1,
    ASSIGNMENT_PLAN_SCHEMA_V1,
    Assignment,
    AssignmentFeedbackDecision,
    AssignmentEvidenceExport,
    AssignmentGuidanceBinding,
    AssignmentMismatchReplaySummary,
    AssignmentPlan,
    AssignmentRecord,
    AssignmentValiditySummary,
    CostWeights,
    DEFAULT_COST_PROFILE_ID,
    DEFAULT_COST_PROFILE_VERSION,
    DEFAULT_FEEDBACK_PROFILE_ID,
    DEFAULT_FEEDBACK_PROFILE_VERSION,
    PlannerConfig,
    ResourceState,
    SECONDARY_PLAN_ACTIVE_STATE,
    SECONDARY_PLAN_SCHEMA_V2,
    SECONDARY_TAKEOVER_READY,
    SolverResult,
    TargetTrack,
    TerminalFeedbackWriteback,
    TERMINAL_FEEDBACK_PROFILE_SCHEMA_V1,
    ThreatScoreBaseline,
    apply_terminal_feedback_to_planner_inputs,
    assignment_evidence_from_plan,
    assignment_records_from_plan,
    assignment_validity_summary_from_plan,
    compose_threat_score_baseline,
    continue_active_secondary_plan,
    evaluate_terminal_feedback,
    guidance_bindings_from_assignment_plan,
    prepare_secondary_takeover_plan,
    summarize_assignment_mismatch_replay,
    summarize_terminal_feedback_calibration,
)
from .planner import AssignmentPlanner, StalePlanError
from .solver import FallbackAssignmentSolver, HungarianAssignmentSolver

__all__ = [
    "ASSIGNMENT_CALIBRATION_PROFILE_SCHEMA_V1",
    "Assignment",
    "ASSIGNMENT_PLAN_SCHEMA_V1",
    "AssignmentFeedbackDecision",
    "AssignmentFixtureStep",
    "AssignmentEvidenceExport",
    "AssignmentGuidanceBinding",
    "AssignmentMismatchReplaySummary",
    "AssignmentPlan",
    "AssignmentPlanner",
    "AssignmentRecord",
    "AssignmentScenarioFixture",
    "AssignmentValiditySummary",
    "AirSimDryRunAssignmentAdapter",
    "CostMatrixResult",
    "CostModel",
    "CostWeights",
    "DEFAULT_COST_PROFILE_ID",
    "DEFAULT_COST_PROFILE_VERSION",
    "DEFAULT_FEEDBACK_PROFILE_ID",
    "DEFAULT_FEEDBACK_PROFILE_VERSION",
    "FallbackAssignmentSolver",
    "HungarianAssignmentSolver",
    "PlannerConfig",
    "P1_ASSIGNMENT_FIXTURE_PROFILE_ID",
    "P1_ASSIGNMENT_FIXTURE_PROFILE_VERSION",
    "P1_ASSIGNMENT_FIXTURE_SCHEMA",
    "ResourceState",
    "SECONDARY_PLAN_ACTIVE_STATE",
    "SECONDARY_PLAN_SCHEMA_V2",
    "SECONDARY_TAKEOVER_READY",
    "SolverResult",
    "StalePlanError",
    "TargetTrack",
    "TerminalFeedbackWriteback",
    "TERMINAL_FEEDBACK_PROFILE_SCHEMA_V1",
    "ThreatScoreBaseline",
    "adapt_airsim_global_tracks",
    "adapt_airsim_resource_states",
    "apply_terminal_feedback_to_planner_inputs",
    "assignment_evidence_from_plan",
    "assignment_records_from_plan",
    "assignment_validity_summary_from_plan",
    "build_p1_assignment_fixtures",
    "compose_threat_score_baseline",
    "continue_active_secondary_plan",
    "evaluate_terminal_feedback",
    "guidance_bindings_from_assignment_plan",
    "prepare_secondary_takeover_plan",
    "p1_assignment_fixture_by_id",
    "summarize_assignment_mismatch_replay",
    "summarize_terminal_feedback_calibration",
]
