"""D3 centralized rolling assignment planner.

This package is for offline research simulation and human-review candidate
planning only. It intentionally excludes real fire-control parameters, damage
logic, hardware drivers, autonomous disposition, and authorization bypasses.
"""

from .costs import CostMatrixResult, CostModel
from .fixtures import (
    P1_ASSIGNMENT_FIXTURE_PROFILE_ID,
    P1_ASSIGNMENT_FIXTURE_PROFILE_VERSION,
    P1_ASSIGNMENT_FIXTURE_SCHEMA,
    AssignmentFixtureStep,
    AssignmentScenarioFixture,
    build_p1_assignment_fixtures,
    p1_assignment_fixture_by_id,
)
from .airsim_dry_run_adapter import (
    AirSimDryRunAssignmentAdapter,
    adapt_airsim_global_tracks,
    adapt_airsim_resource_states,
)
from .models import (
    ASSIGNMENT_CALIBRATION_PROFILE_SCHEMA_V1,
    ASSIGNMENT_PLAN_SCHEMA_V1,
    ASSIGNMENT_PLAN_SCHEMA_V2,
    Assignment,
    AssignmentFeedbackDecision,
    AssignmentEvidenceExport,
    AssignmentGuidanceBinding,
    IncrementalPlanningComparisonSummary,
    AssignmentMismatchReplaySummary,
    AssignmentPlan,
    AssignmentRecord,
    AssignmentValiditySummary,
    CoalitionMember,
    CoalitionMemberRole,
    CoalitionPlan,
    CoalitionState,
    CoalitionSummary,
    CoordinationMode,
    CostWeights,
    DEFAULT_COST_PROFILE_ID,
    DEFAULT_COST_PROFILE_VERSION,
    DEFAULT_FEEDBACK_PROFILE_ID,
    DEFAULT_FEEDBACK_PROFILE_VERSION,
    PlannerConfig,
    ResourceState,
    SECONDARY_PLAN_ACTIVE_STATE,
    SECONDARY_PLAN_SCHEMA_V2,
    SECONDARY_TAKEOVER_READY,
    SolverResult,
    DemandSatisfactionSummary,
    TargetDemand,
    TargetTrack,
    TerminalFeedbackWriteback,
    TERMINAL_FEEDBACK_PROFILE_SCHEMA_V1,
    ThreatScoreBaseline,
    apply_terminal_feedback_to_planner_inputs,
    assignment_evidence_from_plan,
    assignment_records_from_plan,
    assignment_validity_summary_from_plan,
    compose_threat_score_baseline,
    continue_active_secondary_plan,
    evaluate_terminal_feedback,
    guidance_bindings_from_assignment_plan,
    prepare_secondary_takeover_plan,
    summarize_assignment_mismatch_replay,
    summarize_incremental_planning_comparison,
    summarize_terminal_feedback_calibration,
)
from .planner import AssignmentPlanner, StalePlanError
from .calibration import (
    P1AssignmentCalibrationRow,
    P1AssignmentCalibrationSummary,
    run_p1_assignment_calibration_matrix,
)
from .min_cost_flow import MinCostFlowAssignmentSolver, OrToolsUnavailableError
from .p2_benchmark import (
    P2_CAPACITY_BENCHMARK_SCHEMA,
    CapacityBenchmarkAssignment,
    CapacityBenchmarkComparison,
    CapacityBenchmarkOutcome,
    CapacityBenchmarkProblem,
    build_p2_capacity_benchmark_problem,
    run_p2_capacity_benchmark,
)
from .solver import (
    FallbackAssignmentSolver,
    HungarianAssignmentSolver,
    HungarianDemandSlotSolver,
)

__all__ = [
    "ASSIGNMENT_CALIBRATION_PROFILE_SCHEMA_V1",
    "Assignment",
    "ASSIGNMENT_PLAN_SCHEMA_V1",
    "ASSIGNMENT_PLAN_SCHEMA_V2",
    "AssignmentFeedbackDecision",
    "AssignmentFixtureStep",
    "AssignmentEvidenceExport",
    "AssignmentGuidanceBinding",
    "IncrementalPlanningComparisonSummary",
    "AssignmentMismatchReplaySummary",
    "AssignmentPlan",
    "AssignmentPlanner",
    "AssignmentRecord",
    "AssignmentScenarioFixture",
    "AssignmentValiditySummary",
    "CoalitionMember",
    "CoalitionMemberRole",
    "CoalitionPlan",
    "CoalitionState",
    "CoalitionSummary",
    "CoordinationMode",
    "CapacityBenchmarkAssignment",
    "CapacityBenchmarkComparison",
    "CapacityBenchmarkOutcome",
    "CapacityBenchmarkProblem",
    "AirSimDryRunAssignmentAdapter",
    "CostMatrixResult",
    "CostModel",
    "CostWeights",
    "DEFAULT_COST_PROFILE_ID",
    "DEFAULT_COST_PROFILE_VERSION",
    "DEFAULT_FEEDBACK_PROFILE_ID",
    "DEFAULT_FEEDBACK_PROFILE_VERSION",
    "DemandSatisfactionSummary",
    "FallbackAssignmentSolver",
    "HungarianAssignmentSolver",
    "HungarianDemandSlotSolver",
    "MinCostFlowAssignmentSolver",
    "OrToolsUnavailableError",
    "P2_CAPACITY_BENCHMARK_SCHEMA",
    "PlannerConfig",
    "P1_ASSIGNMENT_FIXTURE_PROFILE_ID",
    "P1_ASSIGNMENT_FIXTURE_PROFILE_VERSION",
    "P1_ASSIGNMENT_FIXTURE_SCHEMA",
    "P1AssignmentCalibrationRow",
    "P1AssignmentCalibrationSummary",
    "ResourceState",
    "SECONDARY_PLAN_ACTIVE_STATE",
    "SECONDARY_PLAN_SCHEMA_V2",
    "SECONDARY_TAKEOVER_READY",
    "SolverResult",
    "StalePlanError",
    "TargetTrack",
    "TargetDemand",
    "TerminalFeedbackWriteback",
    "TERMINAL_FEEDBACK_PROFILE_SCHEMA_V1",
    "ThreatScoreBaseline",
    "adapt_airsim_global_tracks",
    "adapt_airsim_resource_states",
    "apply_terminal_feedback_to_planner_inputs",
    "assignment_evidence_from_plan",
    "assignment_records_from_plan",
    "assignment_validity_summary_from_plan",
    "build_p1_assignment_fixtures",
    "build_p2_capacity_benchmark_problem",
    "compose_threat_score_baseline",
    "continue_active_secondary_plan",
    "evaluate_terminal_feedback",
    "guidance_bindings_from_assignment_plan",
    "prepare_secondary_takeover_plan",
    "p1_assignment_fixture_by_id",
    "run_p1_assignment_calibration_matrix",
    "summarize_assignment_mismatch_replay",
    "summarize_incremental_planning_comparison",
    "summarize_terminal_feedback_calibration",
    "run_p2_capacity_benchmark",
]
