"""Offline multi-sensor fusion research module.

The package is intentionally limited to simulation and offline evaluation. It
does not provide real vehicle control, fire-control, or automatic action APIs.
"""

from .airsim_dry_run import (
    AIRSIM_DRY_RUN_FIXTURE_SCHEMA_VERSION,
    make_minimal_airsim_dry_run_fixture,
    observations_from_airsim_dry_run_fixture,
)
from .airsim_replay_freeze import (
    AIRSIM_CAPTURE_PROVENANCE_SCHEMA_VERSION,
    AIRSIM_FREEZE_OUTPUT_SCHEMA_VERSION,
    AIRSIM_FREEZE_SUMMARY_SCHEMA_VERSION,
    AIRSIM_OFFLINE_TRUTH_SCHEMA_VERSION,
    AirSimReplayFreezeResult,
    file_sha256,
    freeze_airsim_replay_file,
    freeze_airsim_replay_payloads,
    load_airsim_replay_payloads,
    write_frozen_airsim_replay,
)
from .cooperative import (
    BearingLocalizationConfig,
    covariance_intersection,
    localize_bearing_observation_group,
)
from .fusion import FusionAdapter
from .long_replay import (
    LONG_REPLAY_CONFIG_VERSION,
    LONG_REPLAY_OFFLINE_TRUTH_SCHEMA_VERSION,
    LONG_REPLAY_SCENARIO_ID,
    LONG_REPLAY_SCENARIO_VERSION,
    LONG_REPLAY_SUMMARY_SCHEMA_VERSION,
    LONG_REPLAY_THRESHOLD_PROFILE_VERSION,
    LongReplayConfig,
    LongReplayScenario,
    LongReplaySummary,
    build_long_replay_scenario,
    summarize_long_replay,
)
from .observations import RadarCovarianceConfig
from .p2_benchmark import (
    OFFLINE_TRUTH_SCHEMA_VERSION,
    P2_BENCHMARK_SCHEMA_VERSION,
    load_frozen_governed_replay,
    run_p2_isolated_benchmark,
)
from .quality import annotate_covariance_growth_rates, summarize_region_quality_windows
from .recon_cue import summarize_recon_cue_from_tracks
from .replay import (
    REPLAY_MANIFEST_SCHEMA_VERSION,
    REPLAY_PROVENANCE_SCHEMA_VERSION,
    REPLAY_SCHEMA_VERSION,
    ReplayProvenance,
    build_governed_replay_manifest,
    read_blocks_sensor_observations_jsonl,
    read_sensor_observations_csv,
    read_sensor_observations_jsonl,
    replay_blocks_sensor_observations_jsonl,
    replay_sensor_observations_csv,
    replay_sensor_observations_jsonl,
    sensor_observation_from_csv_row,
    sensor_observation_from_jsonl_record,
    sensor_observation_to_replay_record,
    serialize_governed_replay,
    serialize_offline_governed_replay,
    summarize_sensor_observation_latency_audit,
    write_sensor_observations_csv,
    write_sensor_observations_jsonl,
)
from .types import (
    CISourceWeight,
    CooperativeBearingObservation,
    CooperativeLocalizationSummary,
    CooperativeObservationGroup,
    CooperativeTrackEstimate,
    CovarianceIntersectionSummary,
    FusionQualityRegionSummary,
    FusionQualityRegionWindowSummary,
    GlobalTrack,
    LatencyAuditSummary,
    LosIntersectionAngle,
    ObserverLineage,
    ReconCueSummary,
    SensorHealthSummary,
    SensorObservation,
    SensorTimingExpectation,
    TrackLevel,
    TrackUncertaintySummary,
)

__all__ = [
    "AIRSIM_CAPTURE_PROVENANCE_SCHEMA_VERSION",
    "AIRSIM_DRY_RUN_FIXTURE_SCHEMA_VERSION",
    "AIRSIM_FREEZE_OUTPUT_SCHEMA_VERSION",
    "AIRSIM_FREEZE_SUMMARY_SCHEMA_VERSION",
    "AIRSIM_OFFLINE_TRUTH_SCHEMA_VERSION",
    "AirSimReplayFreezeResult",
    "BearingLocalizationConfig",
    "CISourceWeight",
    "CooperativeBearingObservation",
    "CooperativeLocalizationSummary",
    "CooperativeObservationGroup",
    "CooperativeTrackEstimate",
    "CovarianceIntersectionSummary",
    "FusionAdapter",
    "FusionQualityRegionSummary",
    "FusionQualityRegionWindowSummary",
    "GlobalTrack",
    "LONG_REPLAY_CONFIG_VERSION",
    "LONG_REPLAY_OFFLINE_TRUTH_SCHEMA_VERSION",
    "LONG_REPLAY_SCENARIO_ID",
    "LONG_REPLAY_SCENARIO_VERSION",
    "LONG_REPLAY_SUMMARY_SCHEMA_VERSION",
    "LONG_REPLAY_THRESHOLD_PROFILE_VERSION",
    "LatencyAuditSummary",
    "LosIntersectionAngle",
    "LongReplayConfig",
    "LongReplayScenario",
    "LongReplaySummary",
    "ObserverLineage",
    "OFFLINE_TRUTH_SCHEMA_VERSION",
    "P2_BENCHMARK_SCHEMA_VERSION",
    "REPLAY_MANIFEST_SCHEMA_VERSION",
    "REPLAY_SCHEMA_VERSION",
    "REPLAY_PROVENANCE_SCHEMA_VERSION",
    "RadarCovarianceConfig",
    "ReconCueSummary",
    "ReplayProvenance",
    "SensorHealthSummary",
    "SensorObservation",
    "SensorTimingExpectation",
    "TrackLevel",
    "TrackUncertaintySummary",
    "annotate_covariance_growth_rates",
    "build_governed_replay_manifest",
    "build_long_replay_scenario",
    "covariance_intersection",
    "file_sha256",
    "freeze_airsim_replay_file",
    "freeze_airsim_replay_payloads",
    "make_minimal_airsim_dry_run_fixture",
    "localize_bearing_observation_group",
    "load_airsim_replay_payloads",
    "load_frozen_governed_replay",
    "observations_from_airsim_dry_run_fixture",
    "read_blocks_sensor_observations_jsonl",
    "read_sensor_observations_csv",
    "read_sensor_observations_jsonl",
    "replay_blocks_sensor_observations_jsonl",
    "replay_sensor_observations_csv",
    "replay_sensor_observations_jsonl",
    "run_p2_isolated_benchmark",
    "sensor_observation_from_csv_row",
    "sensor_observation_from_jsonl_record",
    "sensor_observation_to_replay_record",
    "serialize_governed_replay",
    "serialize_offline_governed_replay",
    "summarize_region_quality_windows",
    "summarize_long_replay",
    "summarize_sensor_observation_latency_audit",
    "write_sensor_observations_csv",
    "write_sensor_observations_jsonl",
    "write_frozen_airsim_replay",
    "summarize_recon_cue_from_tracks",
]
