"""Offline distributed fallback simulation package for D4."""

from .active_degradation import (
    ActiveDegradationArbiter,
    ActiveDegradationConfig,
    ActiveDegradationDecision,
    AssignmentValiditySummary,
    AssociationRiskSummary,
    D7SecondaryHandoff,
    DegradationAction,
    DegradationMode,
    TerminalAssociationSummary,
    TerminalDecisionState,
    TrackUncertaintySummary,
    build_d7_secondary_handoff,
    summarize_secondary_lifecycle,
)
from .adapter import (
    D4ArbitrationAdapter,
    D4ArbitrationResult,
    D4DecisionRecord,
    build_assignment_validity_summary,
    build_association_risk_summary,
    build_communication_summary,
    build_terminal_association_summary,
    build_track_uncertainty_summary,
)
from .cbba import CBBANegotiator
from .coordinator import FailoverCoordinator
from .models import (
    Assignment,
    AvailabilityBand,
    C2Health,
    CommBand,
    CommunicationSummary,
    ConfidenceBand,
    LinkType,
    NodeRole,
    PayloadKind,
    ResourceSummary,
    SecondaryNodeLifecycleSummary,
    TrackSummary,
)

__all__ = [
    "ActiveDegradationArbiter",
    "ActiveDegradationConfig",
    "ActiveDegradationDecision",
    "Assignment",
    "AssignmentValiditySummary",
    "AssociationRiskSummary",
    "AvailabilityBand",
    "C2Health",
    "CBBANegotiator",
    "CommBand",
    "CommunicationSummary",
    "ConfidenceBand",
    "D4ArbitrationAdapter",
    "D4ArbitrationResult",
    "D4DecisionRecord",
    "D7SecondaryHandoff",
    "DegradationAction",
    "DegradationMode",
    "FailoverCoordinator",
    "LinkType",
    "NodeRole",
    "PayloadKind",
    "ResourceSummary",
    "SecondaryNodeLifecycleSummary",
    "TerminalAssociationSummary",
    "TerminalDecisionState",
    "TrackSummary",
    "TrackUncertaintySummary",
    "build_assignment_validity_summary",
    "build_association_risk_summary",
    "build_communication_summary",
    "build_d7_secondary_handoff",
    "build_terminal_association_summary",
    "build_track_uncertainty_summary",
    "summarize_secondary_lifecycle",
]
