"""Offline multi-target data association research module."""

from .associators import (
    DataAssociator,
    GNNHungarianAssociator,
    JPDAAssociator,
    MHTAssociator,
)
from .cross_node_metrics import (
    CrossNodeRegistryMetrics,
    OfflineCrossNodeMetricsEvaluator,
)
from .cross_node_models import (
    BindingHistoryEvent,
    CanonicalTrackSnapshot,
    CorrelationStatus,
    CrossNodeAssociationResult,
    FusionAction,
    FusionDirective,
    RejectedSourceTrack,
    SourceTrackKey,
    SourceTrackSummary,
    TrackToTrackMatch,
)
from .cross_node_registry import (
    CrossNodeAssignmentBatch,
    CrossNodeTrackAssociator,
    CrossNodeTrackRegistry,
)
from .d1_governed_adapter import (
    D1_GOVERNED_MANIFEST_SCHEMA,
    D1_OBSERVATION_SCHEMA,
    d2_frames_from_d1_governed_replay,
    is_d1_governed_replay_payload,
)
from .calibration import (
    DenseCrossingCalibrationReport,
    GateCalibrationProfile,
    run_dense_crossing_calibration,
    summarize_dense_crossing_calibration,
    write_dense_crossing_calibration_report,
)
from .compat import (
    OptionalDependencyStatus,
    OptionalIntegrationUnavailable,
    filterpy_filter_from_detection,
    optional_dependency_status,
    probe_optional_dependency,
    to_filterpy_state,
    to_stonesoup_detection,
)
from .dry_run_adapter import (
    DryRunAssociationFrame,
    DryRunAssociationResult,
    build_default_dry_run_tracker,
    detections_from_d1_global_tracks,
    detections_from_airsim_frame,
    run_airsim_dry_run_association,
)
from .metrics import (
    AssociationRiskSummaryWindowGenerator,
    MetricsRecorder,
    RiskBreakdown,
    RiskThresholds,
    classify_risk_summary,
)
from .offline_truth import (
    OFFLINE_TRUTH_SCHEMA_VERSION,
    OfflineTruthLabel,
    evaluation_frames_with_offline_truth,
    extract_offline_truth_labels,
    load_offline_truth_labels_jsonl,
    strip_offline_truth_from_frames,
    write_offline_truth_labels_jsonl,
)
from .p2_benchmark import (
    OptionalBenchmarkResult,
    P2BenchmarkReport,
    run_optional_framework_benchmark,
    write_p2_benchmark_report,
)
from .replay import (
    ReplayAssociationReport,
    load_airsim_replay_frames,
    run_airsim_replay_association,
    run_threshold_sensitivity,
    summarize_replay_risk,
    summarize_multi_seed_risk_calibration,
    write_association_logs_jsonl,
    write_replay_association_report,
)
from .replay_governance import (
    InitializationGovernanceProfile,
    OfflineTruthEvaluation,
    build_5v5_replay_fixture,
    build_dense_crossing_replay_fixture,
    evaluate_offline_truth,
)
from .models import (
    AssociationLogEntry,
    AssociationResult,
    AssociationRiskSummary,
    Detection,
    GlobalTrack,
    MatchedPair,
    RejectedPair,
    TrackLifecycleState,
    TrackTransition,
)
from .tracker import Tracker

__all__ = [
    "AssociationLogEntry",
    "BindingHistoryEvent",
    "CanonicalTrackSnapshot",
    "CorrelationStatus",
    "CrossNodeAssociationResult",
    "CrossNodeAssignmentBatch",
    "CrossNodeRegistryMetrics",
    "CrossNodeTrackAssociator",
    "CrossNodeTrackRegistry",
    "DenseCrossingCalibrationReport",
    "AssociationRiskSummaryWindowGenerator",
    "AssociationRiskSummary",
    "InitializationGovernanceProfile",
    "OfflineTruthEvaluation",
    "AssociationResult",
    "DataAssociator",
    "D1_GOVERNED_MANIFEST_SCHEMA",
    "D1_OBSERVATION_SCHEMA",
    "Detection",
    "DryRunAssociationFrame",
    "DryRunAssociationResult",
    "GNNHungarianAssociator",
    "GateCalibrationProfile",
    "GlobalTrack",
    "FusionAction",
    "FusionDirective",
    "JPDAAssociator",
    "MHTAssociator",
    "MatchedPair",
    "MetricsRecorder",
    "OfflineCrossNodeMetricsEvaluator",
    "OFFLINE_TRUTH_SCHEMA_VERSION",
    "OfflineTruthLabel",
    "OptionalBenchmarkResult",
    "OptionalDependencyStatus",
    "OptionalIntegrationUnavailable",
    "P2BenchmarkReport",
    "RiskBreakdown",
    "RiskThresholds",
    "ReplayAssociationReport",
    "classify_risk_summary",
    "load_airsim_replay_frames",
    "run_airsim_replay_association",
    "run_threshold_sensitivity",
    "summarize_multi_seed_risk_calibration",
    "summarize_replay_risk",
    "write_association_logs_jsonl",
    "write_replay_association_report",
    "RejectedPair",
    "RejectedSourceTrack",
    "SourceTrackKey",
    "SourceTrackSummary",
    "TrackLifecycleState",
    "TrackTransition",
    "TrackToTrackMatch",
    "Tracker",
    "build_default_dry_run_tracker",
    "build_5v5_replay_fixture",
    "build_dense_crossing_replay_fixture",
    "detections_from_d1_global_tracks",
    "d2_frames_from_d1_governed_replay",
    "evaluate_offline_truth",
    "evaluation_frames_with_offline_truth",
    "extract_offline_truth_labels",
    "filterpy_filter_from_detection",
    "load_offline_truth_labels_jsonl",
    "is_d1_governed_replay_payload",
    "optional_dependency_status",
    "probe_optional_dependency",
    "detections_from_airsim_frame",
    "run_airsim_dry_run_association",
    "run_dense_crossing_calibration",
    "run_optional_framework_benchmark",
    "strip_offline_truth_from_frames",
    "summarize_dense_crossing_calibration",
    "to_filterpy_state",
    "to_stonesoup_detection",
    "write_dense_crossing_calibration_report",
    "write_offline_truth_labels_jsonl",
    "write_p2_benchmark_report",
]
