"""Offline multi-target data association research module."""

from .associators import (
    DataAssociator,
    GNNHungarianAssociator,
    JPDAAssociator,
    MHTAssociator,
)
from .cross_node_metrics import (
    CrossNodeRegistryMetrics,
    OfflineCrossNodeMetricsEvaluator,
)
from .cross_node_models import (
    BindingHistoryEvent,
    CanonicalTrackSnapshot,
    CorrelationStatus,
    CrossNodeAssociationResult,
    FusionAction,
    FusionDirective,
    RejectedSourceTrack,
    SourceTrackKey,
    SourceTrackSummary,
    TrackToTrackMatch,
)
from .cross_node_registry import (
    CrossNodeAssignmentBatch,
    CrossNodeTrackAssociator,
    CrossNodeTrackRegistry,
)
from .dry_run_adapter import (
    DryRunAssociationFrame,
    DryRunAssociationResult,
    build_default_dry_run_tracker,
    detections_from_d1_global_tracks,
    detections_from_airsim_frame,
    run_airsim_dry_run_association,
)
from .metrics import (
    AssociationRiskSummaryWindowGenerator,
    MetricsRecorder,
    RiskBreakdown,
    RiskThresholds,
    classify_risk_summary,
)
from .replay import (
    ReplayAssociationReport,
    load_airsim_replay_frames,
    run_airsim_replay_association,
    run_threshold_sensitivity,
    summarize_replay_risk,
    summarize_multi_seed_risk_calibration,
    write_association_logs_jsonl,
    write_replay_association_report,
)
from .replay_governance import (
    InitializationGovernanceProfile,
    OfflineTruthEvaluation,
    build_5v5_replay_fixture,
    evaluate_offline_truth,
)
from .models import (
    AssociationLogEntry,
    AssociationResult,
    AssociationRiskSummary,
    Detection,
    GlobalTrack,
    MatchedPair,
    RejectedPair,
    TrackLifecycleState,
    TrackTransition,
)
from .tracker import Tracker

__all__ = [
    "AssociationLogEntry",
    "BindingHistoryEvent",
    "CanonicalTrackSnapshot",
    "CorrelationStatus",
    "CrossNodeAssociationResult",
    "CrossNodeAssignmentBatch",
    "CrossNodeRegistryMetrics",
    "CrossNodeTrackAssociator",
    "CrossNodeTrackRegistry",
    "AssociationRiskSummaryWindowGenerator",
    "AssociationRiskSummary",
    "InitializationGovernanceProfile",
    "OfflineTruthEvaluation",
    "AssociationResult",
    "DataAssociator",
    "Detection",
    "DryRunAssociationFrame",
    "DryRunAssociationResult",
    "GNNHungarianAssociator",
    "GlobalTrack",
    "FusionAction",
    "FusionDirective",
    "JPDAAssociator",
    "MHTAssociator",
    "MatchedPair",
    "MetricsRecorder",
    "OfflineCrossNodeMetricsEvaluator",
    "RiskBreakdown",
    "RiskThresholds",
    "ReplayAssociationReport",
    "classify_risk_summary",
    "load_airsim_replay_frames",
    "run_airsim_replay_association",
    "run_threshold_sensitivity",
    "summarize_multi_seed_risk_calibration",
    "summarize_replay_risk",
    "write_association_logs_jsonl",
    "write_replay_association_report",
    "RejectedPair",
    "RejectedSourceTrack",
    "SourceTrackKey",
    "SourceTrackSummary",
    "TrackLifecycleState",
    "TrackTransition",
    "TrackToTrackMatch",
    "Tracker",
    "build_default_dry_run_tracker",
    "build_5v5_replay_fixture",
    "detections_from_d1_global_tracks",
    "evaluate_offline_truth",
    "detections_from_airsim_frame",
    "run_airsim_dry_run_association",
]
