"""Main-owned scalable three-dimensional point-mass simulation."""

from .camera_projection import (
    CameraIntrinsics,
    CameraPose,
    ProjectionBatch,
    look_at_rotation_ned_to_camera,
    project_points,
)
from .episode_bus import (
    EpisodeManifest,
    InMemoryEpisodeBus,
    VersionedEnvelope,
    assert_online_payload_truth_free,
    build_episode_manifest,
)
from .experiment_matrix import (
    EXPERIMENT_MATRIX_SCHEMA_VERSION,
    EXPERIMENT_VARIANTS,
    ExperimentCell,
    ExperimentMatrixPlan,
    ModelBundlePaths,
    load_training_seeds,
    run_experiment_matrix,
    runtime_options_for_variant,
    validate_required_bundles,
)
from .communication import (
    CommunicationStats,
    DeliveredMessage,
    DeterministicCommunicationNetwork,
    LinkProfile,
)
from .models import (
    BUS_SCHEMA_VERSION,
    OFFLINE_TRUTH_SCHEMA_VERSION,
    ONLINE_OBSERVATION_SCHEMA_VERSION,
    SCENARIO_SCHEMA_VERSION,
    WORLD_SCHEMA_VERSION,
    EntityKind,
    EntitySnapshot,
    KinematicLimits,
    ObservationBatch,
    OnlineSensorBatch,
    OfflineTruthLabel,
    ScenarioConfig,
    SensorMeasurement,
    WorldSnapshot,
)
from .orchestrator import EpisodeResult, Scalable3DEpisodeRunner, run_episode
from .sensor_scene import CameraView, SensorScene
from .scenarios import AVAILABLE_SCENARIOS, SCENARIO_CATALOG_VERSION, make_curriculum_scenario
from .runtime_ports import (
    CameraObservationCommand,
    CameraRuntimeState,
    PlatformNavigationBatch,
    RuntimePublication,
    RuntimeStepInput,
    RuntimeStepOutput,
    ScalableModuleStack,
)
from .module_stack import (
    D4RegionLearningFrame,
    D5GraphLearningFrame,
    D5ActiveVisionLearningFrame,
    INTEGRATED_STACK_SCHEMA_VERSION,
    IntegratedLearningArtifacts,
    IntegratedScalableModuleStack,
    IntegratedStackConfig,
)
from .learning_export import (
    BatchLearningArtifactWriter,
    LEARNING_EXPORT_SCHEMA_VERSION,
    write_episode_learning_artifacts,
)
from .learning_runtime import (
    LearningRuntimeOptions,
    ResolvedLearningRuntime,
    resolve_learning_runtime,
)
from .shared_seed_split import (
    SHARED_SEED_SPLIT_POLICY_VERSION,
    SHARED_SEED_SPLIT_SCHEMA_VERSION,
    SharedSeedSplitError,
    assign_shared_seed_splits,
    build_shared_seed_split_registry,
    load_shared_seed_split_registry,
    write_shared_seed_split_registry,
)
from .reserved_seed_interventions import (
    INTERVENTION_KINDS,
    INTERVENTION_SELECTION_POLICY,
    RESERVED_EVALUATION_SEEDS,
    RESERVED_SEED_INTERVENTION_SCHEMA_VERSION,
    D3DevelopmentBundleBinding,
    InterventionGlobalTrackSnapshot,
    ReservedSeedInterventionExecution,
    ReservedSeedInterventionOptions,
    ReservedSeedSourceBatch,
    ReservedSeedSourceEvidence,
    collect_reserved_seed_sources,
    execute_reserved_seed_interventions,
    resolve_d3_development_bundle_binding,
    write_reserved_seed_intervention_execution,
)
from .isolated_degraded_adoption import (
    D4_ISOLATED_PHYSICAL_ADOPTION_SCHEMA,
    D4IsolatedPhysicalAdoptionRecord,
    evaluate_d4_isolated_physical_adoption,
)
from .isolated_physical_rollout import (
    ISOLATED_PHYSICAL_ROLLOUT_SCHEMA_VERSION,
    CheckpointPhysicalRolloutOptions,
    IsolatedPhysicalArmResult,
    IsolatedPhysicalPairResult,
    IsolatedPhysicalRolloutExecution,
    execute_checkpoint_paired_physical_rollouts,
    write_checkpoint_paired_physical_rollouts,
)
from .world import ProximityInterceptEvent, VectorizedPointMassWorld
from .animation import write_trajectory_animation

__all__ = [
    "BUS_SCHEMA_VERSION",
    "BatchLearningArtifactWriter",
    "AVAILABLE_SCENARIOS",
    "CameraIntrinsics",
    "CameraObservationCommand",
    "CameraPose",
    "CameraRuntimeState",
    "CameraView",
    "CommunicationStats",
    "DeliveredMessage",
    "DeterministicCommunicationNetwork",
    "D4RegionLearningFrame",
    "D4_ISOLATED_PHYSICAL_ADOPTION_SCHEMA",
    "D4IsolatedPhysicalAdoptionRecord",
    "D5GraphLearningFrame",
    "D5ActiveVisionLearningFrame",
    "EntityKind",
    "EntitySnapshot",
    "EXPERIMENT_MATRIX_SCHEMA_VERSION",
    "EXPERIMENT_VARIANTS",
    "ExperimentCell",
    "ExperimentMatrixPlan",
    "EpisodeManifest",
    "EpisodeResult",
    "InMemoryEpisodeBus",
    "INTEGRATED_STACK_SCHEMA_VERSION",
    "IntegratedScalableModuleStack",
    "IntegratedLearningArtifacts",
    "IntegratedStackConfig",
    "KinematicLimits",
    "LinkProfile",
    "LearningRuntimeOptions",
    "LEARNING_EXPORT_SCHEMA_VERSION",
    "ModelBundlePaths",
    "ObservationBatch",
    "OnlineSensorBatch",
    "OFFLINE_TRUTH_SCHEMA_VERSION",
    "OfflineTruthLabel",
    "ONLINE_OBSERVATION_SCHEMA_VERSION",
    "ProjectionBatch",
    "ProximityInterceptEvent",
    "PlatformNavigationBatch",
    "RuntimePublication",
    "RuntimeStepInput",
    "RuntimeStepOutput",
    "ResolvedLearningRuntime",
    "RESERVED_EVALUATION_SEEDS",
    "RESERVED_SEED_INTERVENTION_SCHEMA_VERSION",
    "INTERVENTION_SELECTION_POLICY",
    "INTERVENTION_KINDS",
    "D3DevelopmentBundleBinding",
    "InterventionGlobalTrackSnapshot",
    "ISOLATED_PHYSICAL_ROLLOUT_SCHEMA_VERSION",
    "CheckpointPhysicalRolloutOptions",
    "IsolatedPhysicalArmResult",
    "IsolatedPhysicalPairResult",
    "IsolatedPhysicalRolloutExecution",
    "ReservedSeedInterventionExecution",
    "ReservedSeedInterventionOptions",
    "ReservedSeedSourceBatch",
    "ReservedSeedSourceEvidence",
    "SHARED_SEED_SPLIT_POLICY_VERSION",
    "SHARED_SEED_SPLIT_SCHEMA_VERSION",
    "SCENARIO_SCHEMA_VERSION",
    "SCENARIO_CATALOG_VERSION",
    "Scalable3DEpisodeRunner",
    "ScalableModuleStack",
    "ScenarioConfig",
    "SensorMeasurement",
    "SensorScene",
    "VectorizedPointMassWorld",
    "VersionedEnvelope",
    "WORLD_SCHEMA_VERSION",
    "WorldSnapshot",
    "SharedSeedSplitError",
    "assign_shared_seed_splits",
    "assert_online_payload_truth_free",
    "build_shared_seed_split_registry",
    "build_episode_manifest",
    "look_at_rotation_ned_to_camera",
    "load_training_seeds",
    "load_shared_seed_split_registry",
    "make_curriculum_scenario",
    "project_points",
    "resolve_learning_runtime",
    "resolve_d3_development_bundle_binding",
    "collect_reserved_seed_sources",
    "execute_reserved_seed_interventions",
    "execute_checkpoint_paired_physical_rollouts",
    "evaluate_d4_isolated_physical_adoption",
    "run_episode",
    "run_experiment_matrix",
    "runtime_options_for_variant",
    "validate_required_bundles",
    "write_trajectory_animation",
    "write_episode_learning_artifacts",
    "write_shared_seed_split_registry",
    "write_reserved_seed_intervention_execution",
    "write_checkpoint_paired_physical_rollouts",
]
