"""Terminal visual association research module.

The package only performs offline/simulation association decisions. It never
rewrites center-owned global track identifiers.
"""

from .associator import AssociationConfig, TerminalAssociator
from .airsim_cv_adapter import (
    AirSimCVScenarioSpec,
    TerminalEvidenceSummary,
    TerminalStressMetrics,
    compute_terminal_stress_metrics,
    local_visual_tracks_from_offline_yolo_bytetrack,
    local_visual_tracks_from_sim_detections,
    publish_sim_detections_as_local_observations,
    summarize_degradation_case,
)
from .airsim_geometry import (
    AirSimIntrinsics,
    GeometricAssociationPair,
    GeometricAssociationResult,
    OfflineAssociationMetrics,
    associate_tracks_to_detections_geometrically,
    camera_model_from_airsim_camera_info,
    evaluate_associations_offline,
    intrinsics_from_capture_settings,
    intrinsics_from_width_height_fov,
    rotation_world_to_opencv_camera_from_quaternion,
)
from .consistency import (
    TerminalConsistencyConfig,
    TerminalConsistencyTracker,
    candidate_cost_margin,
    summarize_terminal_consistency,
)
from .identity import IdentityChecker
from .models import (
    Assignment,
    CameraModel,
    CostBreakdown,
    CostMatrixResult,
    CrossPeerAssociationHypothesis,
    CrossViewAssociation,
    DistributedTerminalAssociation,
    DistributedVisualObservation,
    GlobalTrack,
    IdentityClaim,
    LocalVisualTrack,
    PeerCameraState,
    ProjectionResult,
    ReconImageCue,
    TerminalAssociation,
    TerminalConsistencySummary,
    TerminalObservation,
    VisualTrackletSummary,
)
from .terminal_cross_view_fusion import (
    TerminalCrossViewFusion,
    TerminalCrossViewFusionConfig,
)
from .observation_bus import TerminalObservationBus
from .visual_handoff import (
    BBoxStability,
    VisualPngHandoffConfig,
    annotate_visual_png_handoff,
    bbox_area_stability,
    expected_bbox_area_ratio,
    range_band_for_handoff,
)
from .yolo_mot_adapter import (
    DEFAULT_YOLOV8_WEIGHTS_PATH,
    IouFallbackTracker,
    YoloMotAdapter,
    YoloMotAdapterConfig,
    YoloMotFrameResult,
    YoloMotUnavailableError,
)

__all__ = [
    "AssociationConfig",
    "AirSimCVScenarioSpec",
    "AirSimIntrinsics",
    "Assignment",
    "CameraModel",
    "CostBreakdown",
    "CostMatrixResult",
    "CrossPeerAssociationHypothesis",
    "CrossViewAssociation",
    "DistributedTerminalAssociation",
    "DistributedVisualObservation",
    "GeometricAssociationPair",
    "GeometricAssociationResult",
    "GlobalTrack",
    "IdentityChecker",
    "IdentityClaim",
    "IouFallbackTracker",
    "LocalVisualTrack",
    "OfflineAssociationMetrics",
    "PeerCameraState",
    "ProjectionResult",
    "ReconImageCue",
    "TerminalAssociation",
    "TerminalCrossViewFusion",
    "TerminalCrossViewFusionConfig",
    "TerminalConsistencyConfig",
    "TerminalConsistencySummary",
    "TerminalConsistencyTracker",
    "TerminalAssociator",
    "TerminalEvidenceSummary",
    "TerminalObservation",
    "TerminalObservationBus",
    "TerminalStressMetrics",
    "VisualTrackletSummary",
    "BBoxStability",
    "DEFAULT_YOLOV8_WEIGHTS_PATH",
    "VisualPngHandoffConfig",
    "YoloMotAdapter",
    "YoloMotAdapterConfig",
    "YoloMotFrameResult",
    "YoloMotUnavailableError",
    "annotate_visual_png_handoff",
    "associate_tracks_to_detections_geometrically",
    "bbox_area_stability",
    "camera_model_from_airsim_camera_info",
    "compute_terminal_stress_metrics",
    "candidate_cost_margin",
    "evaluate_associations_offline",
    "expected_bbox_area_ratio",
    "intrinsics_from_capture_settings",
    "intrinsics_from_width_height_fov",
    "local_visual_tracks_from_offline_yolo_bytetrack",
    "local_visual_tracks_from_sim_detections",
    "publish_sim_detections_as_local_observations",
    "range_band_for_handoff",
    "rotation_world_to_opencv_camera_from_quaternion",
    "summarize_degradation_case",
    "summarize_terminal_consistency",
]
